server:
  # 应用服务 WEB 访问端口
  port: 8000

spring:
  application:
    # 应用名称
    name: java-spring-applets
    # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: mysql
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/applets?serverTimezone=UTC
    # 数据库用户名&密码
    username: root
    password: 123456
    #创建表的MySql语句位置
    # schema:
    ##插入数据的MySql语句的位置
    # data:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update


swagger:
  title: ${spring.application.name}
  description: ${spring.application.name}接口文档
  version: 1.0.0
  termsOfServiceUrl: http://localhost:8000/doc.html
  contact:
    name: zglong
    url: http://localhost:8000/doc.html
    email: zglong182@qq.com



#************H2  Begin****************
#创建表的MySql语句位置
#spring.datasource.schema=classpath:schema.sql
##插入数据的MySql语句的位置
#spring.datasource.data=classpath:data.sql